  %-----------------------------------------------------%
  % GENERAL DESCRIPTION OF INSTANCE FILE.               %
  %-----------------------------------------------------%
  % // Number of Rows
  % [NR] 
  % 6, 8, 10  
  % // Number of Columns
  % [NC]
  % 50 to 170
  % // Number of Ports
  % [NP]
  % 10, 15, 20, 25, 30
  % // Demand Matriz Type
  % [DT]
  % 1 - Mixed, 2 - Long Distance, 3 - Short Distance 
  % // Demand Matriz Information
  % [DI]
  % 0 10 15 ... 30
  % 0  0 20 ... 13
  % |  |  \  -   |  
  % 0  0  0 ... 25
  %
  % // The name of the file is generated by a combination
  % // of the information for each instance. For example:
  % // stowage06050101 mean:
  %            |  | ||
  %            |  | ||
  %            |  | |v
  %            |  | vMixed Matrix
  %            |  v 10 ports
  %            v  50 columns 
  %            6 rows
  %-----------------------------------------------------%
  %                                                     %
  %-----------------------------------------------------%
  % Chamando funcao de gravacao de dados.
  function gravarD(nr,nc,np,dt,D,sdir)
  
    % Primeiro capturando o diretorio atual.
    diratual = cd;
    
    % Mudando de diretorio para gravar arquivos.
    cd(sdir);
  
     
    % Gerando string com o nome do arquivo.
    aux = sprintf('%02d',nr);
    nome = strcat('stowage',aux);
    aux = sprintf('%03d',nc);
    nome = strcat(nome,aux);
    aux = sprintf('%2d',np);
    nome = strcat(nome,aux);
    aux = sprintf('%d',dt);
    nome = strcat(nome,aux);
    nome = strcat(nome,'.sto');
    
    % Criando e abrindo arquivo, se possivel.
    fid = fopen(nome,'w');
    % Conseguiu criar arquivo com sucesso.
    if (fid ~= -1)
      
      %-------------------------------------------%
      % Cabecalho das principais informacoes.     %
      %-------------------------------------------%
      
      %-------------------------------------------%
      % Informacoes de data e tempo de geracao.   %
      %-------------------------------------------%
      fprintf(fid,'// Date \n');  
      fprintf(fid,'[DA] \n');  
      fprintf(fid,'%s \n',date);  
      fprintf(fid,'// Hour \n');  
      fprintf(fid,'[HO] \n');  
      v = clock;
      fprintf(fid,'%02d:%02d:%02.0f \n',v(4),v(5),v(6));        
      %-------------------------------------------%
      
      
      %-------------------------------------------%
      % Numero de linhas.                         %
      %-------------------------------------------%
      fprintf(fid,'// Number of Rows: 6, 8, 10 \n');  
      fprintf(fid,'[NR] \n');  
      fprintf(fid,'%02d \n',nr);  
      %-------------------------------------------%
      
      %-------------------------------------------%
      % Numero de colunas.                        %
      %-------------------------------------------%
      fprintf(fid,'// Number of Columns: 50 to 170 \n');  
      fprintf(fid,'[NC] \n');  
      fprintf(fid,'%03d \n',nc);  
      %-------------------------------------------%

      %-------------------------------------------%
      % Numero de portos.                         %
      %-------------------------------------------%
      fprintf(fid,'// Number of Ports: 10:5:30 \n');  
      fprintf(fid,'[NP] \n');  
      fprintf(fid,'%2d \n',np);  
      %-------------------------------------------%
      
      %-------------------------------------------%
      % Tipos de matriz.                          %
      %-------------------------------------------%
      fprintf(fid,'// Matrix type: 1 - Mixed, 2 - Long Distance, 3 - Short Distance \n');  
      fprintf(fid,'[DT] \n');  
      fprintf(fid,'%1d \n',dt);  
      %-------------------------------------------%
      
      %-------------------------------------------%
      % Conteudo da matriz D gerada.              %
      %-------------------------------------------%
      fprintf(fid,'// Demand Matriz Information \n');  
      fprintf(fid,'[DI] \n');  
      % Percorrendo cada elemento da matriz D e 
      % imprimindo.
      for i=1:np
        for j=1:np  
          fprintf(fid,' %5d ',D(i,j));  
        end
        fprintf(fid,'\n');
      end  
      %-------------------------------------------%
      
      % Fechando o arquivo apos escrever as informacoes 
      % geradas.
      fclose(fid);
      
    else
      fprintf(1,'Problemas na criação do arquivo %s \n',fid);  
    end    
    
    % Voltando ao diretorio original.
    cd(diratual);